### ISSUE TITLE
Problems with running the app locally on hybrid-angular1-angular2 branch

### ISSUE THREAD

**Issue by vucalur** [ui-router/sample-app-ng1#29]
Could you please revise committed settings?

Steps I take:

1. `$ npm install`
2. `$ npm run dev` (BTW: inconsistency between branches: `dev` vs. `start` in `master` branch)
3. Opened `http://localhost:3000`, got following error:
`Unhandled Promise rejection: (SystemJS) Unable to dynamically transpile ES module as SystemJS.transpiler set to false.`
4. After changing in to `true` in [`config.js`](https://github.com/ui-router/sample-app-ng1/blob/hybrid-angular1-angular2/config.js#L15,`), I get: `Unhandled Promise rejection: (SystemJS) name.lastIndexOf is not a function`

If it's my fault and I'm doing sth wrong, perhaps writing a short note on running the stuff in `README.md` could help.

**Comment by christopherthielen** [comment]
I moved the code from that branch into its own repository.  Can you try https://github.com/ui-router/sample-app-ng1-to-ng2

git clone https://github.com/ui-router/sample-app-ng1-to-ng2.git
cd sample-app-ng1-to-ng2
npm install && npm start

**Comment by vucalur** [comment]
Thanks. Seems to be working.
I only had to change port from `3000` to `3001` in [`index.html`](https://github.com/ui-router/sample-app-ng1-to-ng2/blob/master/index.html#L23). Browser-sync has bound to `3001` for me.

IMHO keeping 2 versions in separate branches is more lucid. One can cherry-pick changes from one to another.
If you'd rather keep it a separate repo, I suggest adding a note about branch depreciation. Deleting a branch with historical commits doesn't sound like a good idea, unless they're moved somewhere else.

With that being said, thanks for a great learning resource!
