### ISSUE TITLE
Build process fails when attempting to mangle the code base

### ISSUE THREAD

**Issue by schester44** [ui-router/sample-app-ng1#34]
I'm using webpack's uglifyjs plugin. The code doesn't work if I have the plugins mangle option set to true. I'm getting an injector provider error on build due to the code not being min-safe. I understand why its happening but I can't figure out the necessary steps needed to not make it happen. I'd imagine the primary root cause would be within ngmodule.js where we actually load everything up.

**Comment by christopherthielen** [comment]
The codebase wasn't minification safe until just recently:

https://github.com/ui-router/sample-app-ng1/commit/2b9d8f8d6e67eed173c098449c4734b560e4a6d4

`mangle` works now, and you can see all the changes required in the above commit.
