### ISSUE TITLE
Lazy Load example

### ISSUE THREAD

**Issue by surfjedi** [ui-router/sample-app-ng1#35]
Any chance of getting a working lazy load example? the docs are that detailed

**Comment by christopherthielen** [comment]
Yes I plan to update with lazy loading and webpack. Also sticky states and dsr

**Comment by christopherthielen** [comment]
@surfjedi the sample app now has lazy loading

https://github.com/ui-router/sample-app-ng1/commit/396484c556e773df142da64ba4318245074d57c0

and sticky states/dsr

https://github.com/ui-router/sample-app-ng1/commit/219ab79040ca5b2db35b5fd10bc9494e29682df3

**Comment by surfjedi** [comment]
Cool thanks!

Curiously I thought we wouldn't need oclazy load?

**Comment by christopherthielen** [comment]
@surfjedi   It's not a trivial to lazy load angular modules.  ocLazyLoad makes it very easy.
